/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RoleRouteImport } from './routes/role'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProducerRouteImport } from './routes/producer'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FilmCommissionRouteImport } from './routes/film-commission'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as ApplyIdRouteImport } from './routes/apply.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerRoute = ProducerRouteImport.update({
  id: '/producer',
  path: '/producer',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmCommissionRoute = FilmCommissionRouteImport.update({
  id: '/film-commission',
  path: '/film-commission',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const ApplyIdRoute = ApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/community': typeof CommunityRoute
  '/film-commission': typeof FilmCommissionRoute
  '/jobs': typeof JobsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/producer': typeof ProducerRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/subscription': typeof SubscriptionRoute
  '/welcome': typeof WelcomeRoute
  '/apply/$id': typeof ApplyIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/messages/$id': typeof MessagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/community': typeof CommunityRoute
  '/film-commission': typeof FilmCommissionRoute
  '/jobs': typeof JobsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/producer': typeof ProducerRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/subscription': typeof SubscriptionRoute
  '/welcome': typeof WelcomeRoute
  '/apply/$id': typeof ApplyIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/messages/$id': typeof MessagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/community': typeof CommunityRoute
  '/film-commission': typeof FilmCommissionRoute
  '/jobs': typeof JobsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/producer': typeof ProducerRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/subscription': typeof SubscriptionRoute
  '/welcome': typeof WelcomeRoute
  '/apply/$id': typeof ApplyIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/messages/$id': typeof MessagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/community'
    | '/film-commission'
    | '/jobs'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/producer'
    | '/profile'
    | '/role'
    | '/saved'
    | '/search'
    | '/settings'
    | '/studio'
    | '/subscription'
    | '/welcome'
    | '/apply/$id'
    | '/jobs/$id'
    | '/messages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/community'
    | '/film-commission'
    | '/jobs'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/producer'
    | '/profile'
    | '/role'
    | '/saved'
    | '/search'
    | '/settings'
    | '/studio'
    | '/subscription'
    | '/welcome'
    | '/apply/$id'
    | '/jobs/$id'
    | '/messages/$id'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/community'
    | '/film-commission'
    | '/jobs'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/producer'
    | '/profile'
    | '/role'
    | '/saved'
    | '/search'
    | '/settings'
    | '/studio'
    | '/subscription'
    | '/welcome'
    | '/apply/$id'
    | '/jobs/$id'
    | '/messages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CommunityRoute: typeof CommunityRoute
  FilmCommissionRoute: typeof FilmCommissionRoute
  JobsRoute: typeof JobsRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProducerRoute: typeof ProducerRoute
  ProfileRoute: typeof ProfileRoute
  RoleRoute: typeof RoleRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  SubscriptionRoute: typeof SubscriptionRoute
  WelcomeRoute: typeof WelcomeRoute
  ApplyIdRoute: typeof ApplyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer': {
      id: '/producer'
      path: '/producer'
      fullPath: '/producer'
      preLoaderRoute: typeof ProducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film-commission': {
      id: '/film-commission'
      path: '/film-commission'
      fullPath: '/film-commission'
      preLoaderRoute: typeof FilmCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/apply/$id': {
      id: '/apply/$id'
      path: '/apply/$id'
      fullPath: '/apply/$id'
      preLoaderRoute: typeof ApplyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  CommunityRoute: CommunityRoute,
  FilmCommissionRoute: FilmCommissionRoute,
  JobsRoute: JobsRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProducerRoute: ProducerRoute,
  ProfileRoute: ProfileRoute,
  RoleRoute: RoleRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  SubscriptionRoute: SubscriptionRoute,
  WelcomeRoute: WelcomeRoute,
  ApplyIdRoute: ApplyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
